let dataBase = {
  foodLunch: [
    {
      id: 1,
      kode: "S96",
      name: "Sate Padang",
      harga: 20000,
      foto: require("./img/satepadang.jpg"),
    },
    {
      id: 2,
      kode: "66",
      name: "Nasi Goreng",
      harga: 15000,
      foto: require("./img/nasigoreng.jpg"),
    },
    {
      id: 3,
      kode: "B6",
      name: "Bakso Telur",
      harga: 13000,
      foto: require("./img/bakso.jpg"),
    },
    {
      id: 4,
      kode: "M61",
      name: "Mie Ayam",
      harga: 15000,
      foto: require("./img/mieayam.jpg"),
    },
    {
      id: 5,
      kode: "I41",
      name: "Indomie Kuah",
      harga: 10000,
      foto: require("./img/indomekuah.jpg"),
    },
  ],
  drinkLunch: [
    {
      id: 6,
      kode: "E21",
      name: "Es Teh",
      harga: 7500,
      foto: require("./img/esteh.jpg"),
    },
    {
      id: 7,
      kode: "K51",
      name: "Kopi",
      harga: 10000,
      foto: require("./img/kopi.jpg"),
    },
    {
      id: 8,
      kode: "L56",
      name: "Lemone Tea",
      harga: 13000,
      foto: require("./img/lemontea.jpg"),
    },
    {
      id: 9,
      kode: "A46",
      name: "Jus Alpukat",
      harga: 15000,
      foto: require("./img/jusalpukat.jpg"),
    },
  ],
  snackLunch: [
    {
      id: 10,
      kode: "R91",
      name: "Roti Bakar",
      harga: 12000,
      foto: require("./img/rotibakar.jpg"),
    },
    {
      id: 11,
      kode: "P76",
      name: "Pisang Crispy",
      harga: 14000,
      foto: require("./img/pisangcrispy.jpg"),
    },
    {
      id: 12,
      kode: "P77",
      name: "Pizza",
      harga: 300000000,
      foto: require("./img/pizza.jpg"),
    },
    {
      id: 13,
      kode: "R92",
      name: "Rujak Buah",
      harga: 9000,
      foto: require("./img/rujakbuah.jpg"),
    },
    {
      id: 14,
      kode: "K52",
      name: "Kentang Goreng",
      harga: 11000,
      foto: require("./img/kentanggoreng.jpg"),
    },
  ],
  imgCarousel: [
    {
      id: 55,
      images: require("./img/kopicaraousel.jpg"),
      tittle: "Kopi",
      subTittle: "Torabika",
      text: '"Rasakan kenikmatan kopi terbaik yang membangunkan selera Anda. Dapatkan pengalaman kopi yang tak terlupakan dengan cita rasa yang memikat."',
    },
    {
      id: 56,
      images: require("./img/roticarousel.jpg"),
      tittle: "Roti",
      subTittle: "Roti Bakar",
      text: '"Nikmati kelezatan roti kami yang segar dan lezat. Setiap gigitan adalah kepuasan bagi lidah Anda. Segera cicipi dan buktikan sendiri!"',
    },
    {
      id: 57,
      images: require("./img/pizzacaraousel.jpg"),
      tittle: "Pizza",
      subTittle: "Pizza Itali",
      text: '"Rasakan kelezatan pizza kami yang tiada tara. Paduan sempurna antara adonan lembut, saus yang kaya rasa, dan topping berkualitas. Puaskan selera Anda dengan setiap gigitan!"',
    },
    {
      id: 58,
      images: require("./img/lemnonteacaraousel.jpg"),
      tittle: "Lemon Tea",
      subTittle: "Pizza Itali",
      text: '"Nikmati keceriaan segar dengan segelas Teh Lemon kami. Menyegarkan dan lezat!"',
    },
  ],
  menuPopuler: [
    {
      id: "foodsatepadang",
      kode: "S96",
      name: "Sate Padang",
      harga: 20000,
      foto: require("./img/satepadang.jpg"),
      text: '"Sate Padang di tempat ini benar-benar menggugah selera! Dagingnya empuk, bumbunya kaya rempah, dan sausnya begitu lezat. Setiap gigitan memberikan sensasi yang menggoyang lidah, benar-benar juara!"',
      komposisi: "Daging, Kunyit, Bumbu Sate, Cabe Rawit",
    },
    {
      id: "foodmieayam",
      kode: "M61",
      name: "Mie Ayam",
      harga: 15000,
      foto: require("./img/mieayam.jpg"),
      text: '"Mie ayam di sini sungguh enak! Kuahnya kaya rasa, mie-nya kenyal, dan topping ayamnya lezat. Rasanya begitu autentik dan mengingatkan saya pada cita rasa mie ayam favorit masa kecil."',
      komposisi: "Mie, Ayam, Daun Bawang, dan Kaldu Ayam",
    },
    {
      id: "foodpisangcrispy",
      kode: "P76",
      name: "Pisang Crispy",
      harga: 14000,
      foto: require("./img/pisangcrispy.jpg"),
      text: '"Pisang crispy ini sungguh luar biasa! Kulitnya yang renyah dan garing sempurna, dengan pisang yang lembut di dalamnya. Rasanya manis dan memuaskan, membuat saya ingin selalu kembali untuk mencicipinya lagi."',
      komposisi: "Pisang, Kezu, Coklat",
    },
    {
      id: "foodkopulatte",
      kode: "K51",
      name: "Kopi",
      harga: 10000,
      foto: require("./img/kopi.jpg"),
      text: '"Tidak ada kata yang bisa menggambarkan betapa memuaskannya secangkir kopi ini. Setiap tegukan membawa kepuasan dan kenikmatan yang tak tergantikan."',
      komposisi: "Kopi hitam dan Air Mendidih",
    },
  ],
};

export default dataBase;
