let dataBase = {
  appetizerFood: [
    {
      id: 1,
      kode: "S96",
      name: "Sate Padang",
      harga: 20000,
      foto: require("./img/satepadang.jpg"),
    },
    {
      id: 2,
      kode: "66",
      name: "Nasi Goreng",
      harga: 15000,
      foto: require("./img/nasigoreng.jpg"),
    },
    {
      id: 3,
      kode: "B6",
      name: "Strawberry Cocktail",
      harga: 13000,
      foto: require("./img/images/strawberrycocktail.jpg"),
    },
    {
      id: 4,
      kode: "M61",
      name: "Bruschetta",
      harga: 15000,
      foto: require("./img/images/bruschetta.jpg"),
    },
    {
      id: 5,
      kode: "I41",
      name: "Tomato Soup",
      harga: 10000,
      foto: require("./img/images/tomatosoup.jpg"),
    },
  ],
  mainCourse: [
    {
      id: 6,
      kode: "E21",
      name: "Steak",
      harga: 7500,
      foto: require("./img/images/steak.jpg"),
    },
    {
      id: 7,
      kode: "K51",
      name: "Pasta",
      harga: 10000,
      foto: require("./img/images/pasta.jpg"),
    },
    {
      id: 8,
      kode: "L56",
      name: "Fresh Sushi",
      harga: 13000,
      foto: require("./img/images/sushi.jpg"),
    },
    {
      id: 9,
      kode: "A46",
      name: "Nachos",
      harga: 15000,
      foto: require("./img/images/nachos.jpg"),
    },
    {
      id: "94hbbyfdg7a83v345nnf3yeg37",
      kode: "C17",
      name: "Cocktail",
      harga: 20000,
      foto: require("./img/cocktail.jpg"),
    },
    {
      id: "asuretwuery7451 b345773456",
      kode: "W90",
      name: "Wine",
      harga: 50000,
      foto: require("./img/wine.jpg"),
    },
  ],
  seaFood: [
    {
      id: 10,
      kode: "R91",
      name: "Roti Bakar",
      harga: 12000,
      foto: require("./img/rotibakar.jpg"),
    },
    {
      id: 11,
      kode: "P76",
      name: "Pisang Crispy",
      harga: 14000,
      foto: require("./img/pisangcrispy.jpg"),
    },
    {
      id: 12,
      kode: "P77",
      name: "Pizza",
      harga: 120000,
      foto: require("./img/pizza.jpg"),
    },
    {
      id: 13,
      kode: "R92",
      name: "Rujak Buah",
      harga: 9000,
      foto: require("./img/rujakbuah.jpg"),
    },
    {
      id: 14,
      kode: "K52",
      name: "Kentang Goreng",
      harga: 11000,
      foto: require("./img/kentanggoreng.jpg"),
    },
  ],
  dessertFood: [
    {
      id: 10,
      kode: "R91",
      name: "Roti Bakar",
      harga: 12000,
      foto: require("./img/rotibakar.jpg"),
    },
    {
      id: 11,
      kode: "P76",
      name: "Pisang Crispy",
      harga: 14000,
      foto: require("./img/pisangcrispy.jpg"),
    },
    {
      id: 12,
      kode: "P77",
      name: "Pizza",
      harga: 120000,
      foto: require("./img/pizza.jpg"),
    },
    {
      id: 13,
      kode: "R92",
      name: "Rujak Buah",
      harga: 9000,
      foto: require("./img/rujakbuah.jpg"),
    },
    {
      id: 14,
      kode: "K52",
      name: "Kentang Goreng",
      harga: 11000,
      foto: require("./img/kentanggoreng.jpg"),
    },
  ],
  fastFood: [
    {
      id: 1,
      kode: "S96",
      name: "Sate Padang",
      harga: 20000,
      foto: require("./img/satepadang.jpg"),
    },
    {
      id: 2,
      kode: "66",
      name: "Nasi Goreng",
      harga: 15000,
      foto: require("./img/nasigoreng.jpg"),
    },
    {
      id: 3,
      kode: "B6",
      name: "Bakso Telur",
      harga: 13000,
      foto: require("./img/bakso.jpg"),
    },
    {
      id: 4,
      kode: "M61",
      name: "Mie Ayam",
      harga: 15000,
      foto: require("./img/mieayam.jpg"),
    },
    {
      id: 5,
      kode: "I41",
      name: "Indomie Kuah",
      harga: 10000,
      foto: require("./img/indomekuah.jpg"),
    },
  ],
  imgCarousel: [
    {
      id: 55,
      images: require("./img/kopicaraousel.jpg"),
      tittle: "Kopi",
      subTittle: "Torabika",
      text: '"Rasakan kenikmatan kopi terbaik yang membangunkan selera Anda. Dapatkan pengalaman kopi yang tak terlupakan dengan cita rasa yang memikat."',
    },
    {
      id: 56,
      images: require("./img/roticarousel.jpg"),
      tittle: "Roti",
      subTittle: "Roti Bakar",
      text: '"Nikmati kelezatan roti kami yang segar dan lezat. Setiap gigitan adalah kepuasan bagi lidah Anda. Segera cicipi dan buktikan sendiri!"',
    },
    {
      id: 57,
      images: require("./img/pizzacaraousel.jpg"),
      tittle: "Pizza",
      subTittle: "Pizza Itali",
      text: '"Rasakan kelezatan pizza kami yang tiada tara. Paduan sempurna antara adonan lembut, saus yang kaya rasa, dan topping berkualitas. Puaskan selera Anda dengan setiap gigitan!"',
    },
    {
      id: 58,
      images: require("./img/lemnonteacaraousel.jpg"),
      tittle: "Lemon Tea",
      subTittle: "Pizza Itali",
      text: '"Nikmati keceriaan segar dengan segelas Teh Lemon kami. Menyegarkan dan lezat!"',
    },
  ],
  menuPopuler: [
    {
      id: "foodsatepadang",
      kode: "S96",
      name: "Sate Padang",
      harga: 20000,
      foto: require("./img/satepadang.jpg"),
      text: '"Sate Padang di tempat ini benar-benar menggugah selera! Dagingnya empuk, bumbunya kaya rempah, dan sausnya begitu lezat. Setiap gigitan memberikan sensasi yang menggoyang lidah, benar-benar juara!"',
      komposisi:
        "Daging sapi, Bumbu marinasi, Bawang putih, Bawang merah, Cabe rawit, Ketumbar, Serai, Gula merah, Gula pasir, Garam, Air asam jawa, Minyak goreng, Air matang",
    },
    {
      id: "foodmieayam",
      kode: "M61",
      name: "Mie Ayam",
      harga: 15000,
      foto: require("./img/mieayam.jpg"),
      text: '"Mie ayam di sini sungguh enak! Kuahnya kaya rasa, mie-nya kenyal, dan topping ayamnya lezat. Rasanya begitu autentik dan mengingatkan saya pada cita rasa mie ayam favorit masa kecil."',
      komposisi:
        "Mie telur, Kaldu ayam, Bawang putih, Bawang merah, Daun bawang, Sawi hijau atau kangkung, Kecap manis, Minyak wijen, Garams, Merica bubuk ",
    },
    {
      id: "foodpisangcrispy",
      kode: "P76",
      name: "Pisang Crispy",
      harga: 14000,
      foto: require("./img/pisangcrispy.jpg"),
      text: '"Pisang crispy ini sungguh luar biasa! Kulitnya yang renyah dan garing sempurna, dengan pisang yang lembut di dalamnya. Rasanya manis dan memuaskan, membuat saya ingin selalu kembali untuk mencicipinya lagi."',
      komposisi:
        "Pisang matang, Tepung terigu, Tepung beras, Coklat batangan, Kejut parut, Air dingin, Gula pasir, Garam, Minyak",
    },
    {
      id: "foodkopulatte",
      kode: "K51",
      name: "Kopi Latte",
      harga: 10000,
      foto: require("./img/kopi.jpg"),
      text: '"Tidak ada kata yang bisa menggambarkan betapa memuaskannya secangkir kopi ini. Setiap tegukan membawa kepuasan dan kenikmatan yang tak tergantikan."',
      komposisi:
        "Kopi bubuk, Air panas, Susu segar, Gula pasir, Ekstrak vanila",
    },
  ],
};

export default dataBase;
